#!/bin/bash

#SBATCH --partition=gpu
#SBATCH --gpus=1
#SBATCH --job-name=Training_Run_%A.out
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=03:00:00
#SBATCH --output=Training_Run_%A.out

module purge
module load 2022
module load Anaconda3/2022.05

source activate porlhf

# Set up wandb API Key
# Fill in the below :)

# export WANDB_API_KEY=

# Run your Python script
python train_reward_model.py